carRentsystemReturn/CarRentSystem2/Models/ReturnCar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rent_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnCar
    {
        public int Id { get; set; }
        public string CarNumber { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime Date { get; set; }
        public int DelayTime { get; set; }
        public int Fine { get; set; }
    }
}

carRentsystemReturn/CarRentSystem2/Controllers/ReturnCarController.cs
using Car_Rent_System.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Car_Rent_System.Controllers
{
    public class ReturnCarController : Controller
    {
        CarRentalEntities1 DB = new CarRentalEntities1();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Save(ReturnCar ReturnCar)
        {
            if (ModelState.IsValid)
            {
                DB.ReturnCars.Add(ReturnCar);
                var car = DB.CarRegisters.SingleOrDefault(carRegister => carRegister.CarNumber == ReturnCar.CarNumber);
                if (car == null)
                {
                    return HttpNotFound("Car Number Not Found!");
                }
                car.Available = "yes";
                DB.Entry(car).State = EntityState.Modified;
                DB.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ReturnCar);
        }
        [HttpPost]
        public ActionResult getId(String CarNumber)
        {
            var carn = (from rental in DB.Rentals
                        where rental.CarId == CarNumber
                        select new
                        {
                            StartDate = rental.StartDate,
                            EndDate = rental.EndDate,
                            CustomerId = rental.CustomerId,
                            CarNumber = rental.CarId,
                            Fee = rental.Fee,
                            DelayDays = SqlFunctions.DateDiff("day", rental.EndDate, DateTime.Now)
                        }).ToArray();
            return Json(carn, JsonRequestBehavior.AllowGet);
        }
    }
}

carRentsystemReturn/CarRentSystem2/Views/ReturnCar/Index.cshtml
<div class="row">
    <div class="col-sm-4">
        @using (Html.BeginForm("Save", "ReturnCar", FormMethod.Post, new { id = "popupForm" }))
        {
            <div>
                <h1>Car Rental</h1>
            </div>
            <div class="form-group">
                <label class="form-lable">Car Number</label>
                <input type="text" id="CarNumber" name="CarNumber"
                       class="form-control" placeholder="Car Number" required />
            </div>
            <div class="form-group">
                <label class="form-lable">Customer ID</label>
                <input type="text" id="CustomerId" name="CustomerId"
                       class="form-control" placeholder="Customer ID" required />
            </div>
            <div class="form-group">
                <label class="form-lable">Date</label>
                <input type="text" id="Date" name="Date"
                       class="form-control" placeholder="Date" required />
            </div>
            <div class="form-group">
                <label class="form-lable">Delay Time</label>
                <input type="text" id="DelayTime" name="DelayTime"
                       class="form-control" placeholder="Customer Name" required />
            </div>
            <div class="form-group">
                <label class="form-lable">Fine</label>
                <input type="text" id="Fine" name="Fine"
                       class="form-control" placeholder="Fine" required />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        }
    </div>
</div>
@section scripts
{
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script>
    getCarId();
        function getCarId() {
            $("#CarNumber").keyup(function (e) {
                $.ajax({
                    type: 'Post',
                    url: '/ReturnCar/getId?CarNumber=' + $("#CarNumber").val(),
                    dataType: 'Json',
                    success: function (data) {
                        console.log(data)
                        $('#CustomerId').val(data[0].CustomerId);
                        $('#Date').val(new Date(parseInt(data[0].EndDate.substring(6))).toLocaleString());
                        $('#DelayTime').val(data[0].DelayDays);
                        var DelayTime = data[0].DelayDays;
                        if (DelayTime > 0) {
                            var Fine = DelayTime * 100;
                            $('#Fine').val(Fine.toString());
                        }
                        else {
                            $('#Fine').val("0");
                        }
                    }
                });
            });
        }
    </script>
}